services:
  mongodb:
    image: mongo:7
    container_name: freeskincare
    environment:
      - MONGODB_DISABLE_SYSTEM_CHECKS=1
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped

volumes:
  mongodb_data:
